### ISSUE TITLE
Morning session peer to peer review 

### ISSUE THREAD

**Issue by djo1975** [martinkarugaba/pokemon-dashboard#26]
Look awesome for now, just keep going guys :)

**Comment by djo1975** [comment]
Hi guys, I expected more from you :) . 
I checked your project and I am disappointed. 
-When you open the home page, you can't see the number of likes before you click on the heart icon.   
-When you send comment page, automatically refresh the browser and closing popup window.
-There is no logo image.....
How this project is approved?
Please follow this link to see how this project has to work :) : https://gilded-biscochitos-2d3114.netlify.app/

**Comment by PowerLevel9000** [comment]
@djo1975  check the link we provided in readme please
